Badges logic implemented.
MrAlejandro/TestGuru pull request #18
Opened 2019-03-17 12:26 UTC by MrAlejandro

2019-03-18 08:16 UTC, BubuntuClu requested changes

2019-03-18 08:16 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:name, :image_url, :quantity_condition, :test_level, :first_try, :category_id)
а если новые правила добавятся? будешь новое поле добавлять в БД? это вообще не вариант. лучше тогда сделать модель Rule какое-нибудь и к нему сделать связь

2019-03-18 08:16 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      BadgesService.new(current_user).give_badges!(@test_passage)
👍

2019-03-18 08:16 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    meet_first_try_condition?(badge, test_passage) ||
потом будут новые методы и это условие будет разрастаться?

2019-03-18 08:16 UTC, BubuntuClu commented on app/services/badges_service.rb
> +  def initialize(user)
тут можно сделать константу с правилами, или брать их из модели `Rule`.

2019-03-18 08:16 UTC, BubuntuClu commented on app/services/badges_service.rb
> +      if eligible_for_badge?(badge, test_passage)
тут на основе имени правила, можно сделать `send "#{rule_name}_award?, badge` и уже в этих методах проверять подходит ли бейдж по условию

2019-03-18 08:16 UTC, BubuntuClu commented on db/schema.rb
> +    t.integer "quantity_condition", null: false
эта структура таблицы плохая.

2019-03-26 15:58 UTC, MrAlejandro commented on db/schema.rb
> +    t.integer "quantity_condition", null: false
fixed

2019-03-26 16:01 UTC, MrAlejandro commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:name, :image_url, :quantity_condition, :test_level, :first_try, :category_id)
fixed

2019-03-26 16:25 UTC, MrAlejandro commented on app/services/badges_service.rb
> +      if eligible_for_badge?(badge, test_passage)
fixed

2019-03-26 16:26 UTC, MrAlejandro commented on app/services/badges_service.rb
> +    meet_first_try_condition?(badge, test_passage) ||
fixed

2019-03-26 16:27 UTC, MrAlejandro commented on app/services/badges_service.rb
> +  def initialize(user)
немного по другому сделал, без хардкода, просто если пройти все тесты из одной категории, или все тесты одного уровня.

2019-03-26 18:09 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :exclude, ->(test_ids) { where("id NOT IN (?)", test_ids.is_a?(Array) ? test_ids : [test_ids]) }
`where.not(id: test_ids)`

2019-03-26 18:09 UTC, BubuntuClu commented on db/migrate/20190317112330_add_score_to_test_passages.rb
> +    add_column :test_passages, :score, :float
можно было сделать поле `passed` типа `boolean`. тогда у тебя была бы проверка просто на `true/false`

2019-03-26 18:09 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    binding.irb
выкатил в прод и у тебя зависло выполнение)

2019-03-26 18:09 UTC, BubuntuClu commented on app/services/badges_service.rb
> +      .exclude(test_passage.id)
`@user.test_passages.for_tests(test_passage.test_id).count == 1`

2019-03-26 18:09 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    return false unless test_passage.passed?
эту проверку ты можешь сделать до инициации сервиса [тут](https://github.com/MrAlejandro/TestGuru/pull/18/files?file-filters%5B%5D=.erb&file-filters%5B%5D=.rb&file-filters%5B%5D=.scss#diff-a4f5a8b1a6717196d57cfe500fa22509R17)

2019-03-26 18:09 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    passed_all_from_category?(test_passage.test.category_id)
зачем тебе метод, который просто вызывает другой метод? ты же результат тут никак не обрабатываешь, а просто используешь. в таком методе нет смысла

2019-03-26 18:09 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    passed_from_the_first_try?(test_passage)
тоже самое

2019-03-26 18:09 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    passed_all_with_level?(test_passage.test.level)
и тут

2019-03-28 17:59 UTC, MrAlejandro commented on app/models/test.rb
> +  scope :exclude, ->(test_ids) { where("id NOT IN (?)", test_ids.is_a?(Array) ? test_ids : [test_ids]) }
fixed

2019-03-28 17:59 UTC, MrAlejandro commented on app/services/badges_service.rb
> +    binding.irb
removed

2019-03-28 18:00 UTC, MrAlejandro commented on app/services/badges_service.rb
> +      .exclude(test_passage.id)
done

2019-03-28 18:05 UTC, MrAlejandro commented on app/services/badges_service.rb
> +    return false unless test_passage.passed?
не хочется выносить отсюда проверку, потому что завтра может добавиться бейдж за 10 проваленных подряд тестов, и прийдется искать все места вызова `give_badges!` и удалять оттуда условие. И `rubocop` ругается если проверку туда добавить `test_passage.passed?`

2019-03-28 18:06 UTC, MrAlejandro commented on app/services/badges_service.rb
> +    passed_all_from_category?(test_passage.test.category_id)
смысл в читаемости, `passed_all_from_category?` легче понять, чем 3 строки кода
```
    test_ids = Test.by_category(category_id).pluck(:id)
    passed_test_ids = @user.test_passages.for_tests(test_ids).passed.pluck(:test_id)
    test_ids.count == passed_test_ids.count
```

2019-03-28 18:07 UTC, merged