Lesson 6
MrAlejandro/TestGuru pull request #5
Opened 2019-02-23 15:53 UTC by MrAlejandro

2019-02-23 20:32 UTC, BubuntuClu requested changes

2019-02-23 20:32 UTC, BubuntuClu commented on app/models/question.rb
> +    errors.add(:answers, "Number of answers must be from 1 to 4.") unless answers.size.between?(1, 4)
это проверка должна быть при создании ответа. валидация вопроса не происходит при сохранении ответа

2019-02-23 20:32 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests, -> {distinct}, through: :test_results
`-> {distinct}` что тебе дает эта конструкция?

2019-02-24 05:52 UTC, MrAlejandro commented on app/models/user.rb
> +  has_many :tests, -> {distinct}, through: :test_results
Пользователь может проходить один тест несколько раз, при обращении к `user.tests` будут дубликаты, пример данных можно увидеть в `seeds.rb`

2019-02-24 06:16 UTC, MrAlejandro commented on app/models/question.rb
> +    errors.add(:answers, "Number of answers must be from 1 to 4.") unless answers.size.between?(1, 4)
done

2019-02-24 07:48 UTC, BubuntuClu commented on app/models/answer.rb
>    belongs_to :question, optional: true
если сделать ` belongs_to :question`(без `optional: true`), то ниже будет код 
```
def validate_question_answers_number
  errors.add(:answers, "question already have 4 answers.") if question.answers.count >= 4
end
```

зачем нам нужны ответы, которые не привязаны к вопросам?

2019-02-24 07:48 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests, -> {distinct}, through: :test_results
хорошо, только потом не забудь, что у тебя такая фильтрация происходит в скоупе)
может помешать потом

2019-02-24 09:06 UTC, MrAlejandro commented on app/models/answer.rb
>    belongs_to :question, optional: true
done

2019-02-24 09:07 UTC, merged